export * from "./coordenadas";
export * from "./listado";
export * from "./queryParams";
export * from "./insert-many-result";
export * from "./socket-message";
export * from "./exactly";
export * from "./deviceInfo";
export * from "./tenentInfo";
export * from "./tipoDispositivo";
